name: VUIC React - Build and Publish to NPM

on:
  push:
    branches: [main]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Necessary for actions/checkout to fetch all history for versioning

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Automatic Version Bump
        id: autobump
        uses: phips28/gh-action-bump-version@v6.0.0
        with:
          tag-prefix: "" # This removes the 'v' prefix from tags if you don't want it
          commit-message: "Bump version to {{version}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
